<Project Sdk="Microsoft.NET.Sdk">

    <PropertyGroup>
        <TargetFramework>net10.0</TargetFramework>
        <LangVersion>14</LangVersion>
        <ImplicitUsings>enable</ImplicitUsings>
        <Nullable>enable</Nullable>
    </PropertyGroup>

    <ItemGroup>
      <PackageReference Include="TUnit" Version="1.68.17" />
    </ItemGroup>

    <ItemGroup>
      <ProjectReference Include="..\Rmg.Core\Rmg.Core.csproj" />
      <ProjectReference Include="..\Rmg\Rmg.csproj" />
    </ItemGroup>

</Project>
