<Project Sdk="Microsoft.NET.Sdk">

    <PropertyGroup>
        <TargetFramework>net5.0</TargetFramework>
        <OutputType>Library</OutputType>
    </PropertyGroup>

    <ItemGroup>
      <PackageReference Include="FluentAssertions" Version="5.10.3" />
      <PackageReference Include="Microsoft.NET.Test.Sdk" Version="16.10.0" />
      <PackageReference Include="xunit" Version="2.4.1" />
      <PackageReference Include="xunit.runner.visualstudio" Version="2.4.3">
        <PrivateAssets>all</PrivateAssets>
        <IncludeAssets>runtime; build; native; contentfiles; analyzers; buildtransitive</IncludeAssets>
      </PackageReference>
    </ItemGroup>

    <ItemGroup>
      <Compile Include="Assertions.fs" />
      <Compile Include="intToBytes.fs" />
      <Compile Include="Probability\GeometricIntProbabilityFunction.fs" />
      <Compile Include="Probability\PickItemWeighted.fs" />
      <Compile Include="StateTimeline\OfSeq.fs" />
      <Compile Include="StateTimeline\TryFindEffectiveIndex.fs" />
      <Compile Include="StateTimeline\Concat.fs" />
      <Compile Include="StateTimeline\ShiftValue.fs" />
      <Compile Include="Timeline\TrimDuration.fs" />
    </ItemGroup>

    <ItemGroup>
      <ProjectReference Include="..\RMG.Core\RMG.Core.fsproj" />
    </ItemGroup>

</Project>
