<Project Sdk="Microsoft.NET.Sdk">

    <PropertyGroup>
        <TargetFramework>netcoreapp3.1</TargetFramework>
    </PropertyGroup>

    <ItemGroup>
      <PackageReference Include="FluentAssertions" Version="5.10.3" />
      <PackageReference Include="Microsoft.NET.Test.Sdk" Version="16.7.1" />
      <PackageReference Include="xunit" Version="2.4.1" />
      <PackageReference Include="xunit.runner.visualstudio" Version="2.4.3">
        <PrivateAssets>all</PrivateAssets>
        <IncludeAssets>runtime; build; native; contentfiles; analyzers; buildtransitive</IncludeAssets>
      </PackageReference>
    </ItemGroup>

    <ItemGroup>
      <Compile Include="Assertions.fs" />
      <Compile Include="Timeline\Flatten.fs" />
      <Compile Include="Timeline\Merge.fs" />
      <Compile Include="Timeline\Trim.fs" />
      <Compile Include="Timeline\Aggregate.fs" />
      <Compile Include="Timeline\WithDuration.fs" />
      <Compile Include="Music\MergeNoteOffsetTimelineMaps.fs" />
      <Compile Include="Composition\Pattern\Flatten.fs" />
      <Compile Include="Composition\Pattern\Map.fs" />
      <Compile Include="Composition\Pattern\FlattenAggregate.fs" />
      <Compile Include="Composition\NoteOffsetBasedPattern\Flatten.fs" />
      <Compile Include="Composition\NoteOffsetPatternMap\Flatten.fs" />
    </ItemGroup>

    <ItemGroup>
      <ProjectReference Include="..\RMG.CoreF\RMG.CoreF.fsproj" />
    </ItemGroup>

</Project>
