<Project Sdk="Microsoft.NET.Sdk">

    <PropertyGroup>
        <TargetFramework>netcoreapp3.1</TargetFramework>
    </PropertyGroup>

    <ItemGroup>
      <PackageReference Include="FluentAssertions" Version="5.10.3" />
      <PackageReference Include="Microsoft.NET.Test.Sdk" Version="16.7.1" />
      <PackageReference Include="xunit" Version="2.4.1" />
      <PackageReference Include="xunit.runner.visualstudio" Version="2.4.3">
        <PrivateAssets>all</PrivateAssets>
        <IncludeAssets>runtime; build; native; contentfiles; analyzers; buildtransitive</IncludeAssets>
      </PackageReference>
    </ItemGroup>

    <ItemGroup>
      <Compile Include="Assertions.fs" />
      <Compile Include="StateTimeline.fs" />
      <Compile Include="intToBytes.fs" />
      <Compile Include="Midi.fs" />
      <Compile Include="Composition\EventPattern.fs" />
      <Compile Include="Composition\StatePattern.fs" />
      <Compile Include="Composition\NoteOffsetStatePatternMap.fs" />
      <Compile Include="Composition\NoteOffsetStateBasedEventPattern.fs" />
      <Compile Include="Composition\TrackNoteOffsetStateBasedEventTimelineMapTest.fs" />
      <Compile Include="Probability\GeometricIntProbabilityFunction.fs" />
      <Compile Include="Probability\PickItemWeighted.fs" />
      <Compile Include="GenerateSong.fs" />
    </ItemGroup>

    <ItemGroup>
      <ProjectReference Include="..\RMG.CoreF\RMG.CoreF.fsproj" />
    </ItemGroup>

</Project>
