<Project Sdk="Microsoft.NET.Sdk">

    <PropertyGroup>
        <TargetFramework>net5.0</TargetFramework>
    </PropertyGroup>

    <ItemGroup>
        <Compile Include="Tuples.fs" />
        <Compile Include="Operators.fs" />
        <Compile Include="CoreTypes.fs" />
        <Compile Include="Event.fs" />
        <Compile Include="Timeline\TimelineArray.fs" />
        <Compile Include="Timeline\Timeline.fs" />
        <Compile Include="Timeline\StateTimeline.fs" />
        <Compile Include="Timeline\EventStateTimelineMap.fs" />
        <Compile Include="Timeline\TrackEventStateTimelineMap.fs" />
        <Compile Include="Instrument.fs" />
        <Compile Include="InstrumentTrack.fs" />
        <Compile Include="Song.fs" />
        <Compile Include="Composition\EventStatePattern.fs" />
        <Compile Include="Composition\TrackEventStatePattern.fs" />
        <Compile Include="Composition\EventStateSongPattern.fs" />
        <Compile Include="Rendering.fs" />
        <Compile Include="Probability.fs" />
        <Compile Include="Generate.fs" />
        <Compile Include="Midi.fs" />
        <Compile Include="RandomMusicGenerator.fs" />
    </ItemGroup>

    <ItemGroup>
      <PackageReference Include="MathNet.Numerics" Version="4.15.0" />
      <PackageReference Include="MathNet.Numerics.FSharp" Version="4.15.0" />
    </ItemGroup>

</Project>
