<Project Sdk="Microsoft.NET.Sdk">

    <PropertyGroup>
        <TargetFramework>netcoreapp3.1</TargetFramework>
    </PropertyGroup>

    <ItemGroup>
        <Compile Include="Operators.fs" />
        <Compile Include="CoreTypes.fs" />
        <Compile Include="NoteOffset.fs" />
        <Compile Include="Timeline\Timeline.fs" />
        <Compile Include="Timeline\EventTimeline.fs" />
        <Compile Include="Timeline\StateTimeline.fs" />
        <Compile Include="Timeline\NoteOffsetStateTimelineMap.fs" />
        <Compile Include="Timeline\NoteOffsetStateBasedEventTimeline.fs" />
        <Compile Include="Timeline\TrackNoteOffsetStateBasedEventTimelineMap.fs" />
        <Compile Include="Song.fs" />
        <Compile Include="Composition\EventPattern.fs" />
        <Compile Include="Composition\StatePattern.fs" />
        <Compile Include="Composition\NoteOffsetStatePatternMap.fs" />
        <Compile Include="Composition\NoteOffsetStateBasedEventPattern.fs" />
        <Compile Include="Composition\TrackNoteOffsetStateBasedEventPatternMap.fs" />
        <Compile Include="Composition\SongPatternMap.fs" />
        <Compile Include="Rendering.fs" />
        <Compile Include="Probability.fs" />
        <Compile Include="Generate.fs" />
        <Compile Include="Midi.fs" />
        <Compile Include="RandomMusicGenerator.fs" />
    </ItemGroup>

    <ItemGroup>
      <PackageReference Include="MathNet.Numerics" Version="4.15.0" />
      <PackageReference Include="MathNet.Numerics.FSharp" Version="4.15.0" />
    </ItemGroup>

</Project>
